import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Container, Navbar } from "react-bootstrap";
import AppHeader from "./components/Headers";
import { Lora } from 'next/font/google'
import { ReactLenis } from '@studio-freight/react-lenis'
import FooterDaNang from "./components/Footer";
import { CartProvider } from "./components/Giohang";
import FloatingCardButton from "./components/FloatingCardButton";
import CardDrawer from "./components/CardDrawer";
import QuickContactBar from "./components/Icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lora = Lora({
  subsets: ['latin', 'vietnamese'], // Bắt buộc có vietnamese để hiển thị dấu chuẩn
  display: 'swap',
  weight: ['400', '500', '600', '700'], // Các độ đậm nhạt bạn muốn dùng
  style: ['normal', 'italic'],          // Cho phép dùng chữ nghiêng
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={lora.className}>
        <CartProvider>
          <QuickContactBar />
          <AppHeader />
          <Navbar /> 
          {children}
          <FloatingCardButton />
          <CardDrawer />
        </CartProvider>
    
        <FooterDaNang />

      </body>
    </html>
  );
}
